# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('instrument', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('founding_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Band'),
        ),
    ]
