# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20171214_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
