# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180120_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instrument',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
