# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180120_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='band',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Band'),
        ),
    ]
