# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180120_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
