# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180120_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='photo',
        ),
    ]
