# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instrument',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.TextField(default='', max_length=20),
        ),
    ]
