# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180121_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=20),
        ),
    ]
