# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180121_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
    ]
